# Generated by Django 5.1.4 on 2024-12-13 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_medicalform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalform',
            name='consent',
        ),
    ]
